export const MAPS = {
  apartment: {
    name: "Perry's Apartment",
    width: 20, height: 15,
    startPos: { x: 5, y: 7 },
    encounterRate: 0.12,
    tileData: [
      "####################",
      "#........#.........#",
      "#.G....V.#...EE..G.#",
      "#........#...EE....#",
      "#.LLL..G...........#",
      "#.LLL..............#",
      "#..................#",
      "#..FF..G...G.KKK...#",
      "#..FF........K.K...#",
      "#..................#",
      "#.G......###..#####",
      "#..........#..#.A.#",
      "#..........#..#...#",
      "#....G.....#.G#.Q.#",
      "####################",
    ],
    exits: [
      { x: 9, y: 13, toMap: 'reseda', toX: 5, toY: 3, label: "Reseda City" },
    ],
    tileColors: {
      '.': '#8B7355', '#': '#555', 'L': '#9B8B6B', 'E': '#4a4a5a', 'F': '#8B6914',
      'V': '#222', 'K': '#6B5B4B', 'Q': '#ddd', 'A': '#bbb', 'G': '#6B5B00',
      'D': '#8B4513', 'S': '#aaa', 'R': '#555', 'r': '#555',
    },
    solidTiles: new Set(['#', 'L', 'E', 'F', 'V', 'K', 'Q', 'A']),
    encounterTiles: new Set(['.']),
    interactTiles: {
      'V': ["Perry stares at the TV. It's showing an infomercial for a mop. Ironic."],
      'Q': ["Perry looks at the toilet. It's seen better days... much better days."],
      'E': ["The bed is covered in clothes, food wrappers, and what might be a laptop."],
      'L': ["The couch has achieved sentience. Or at least it smells like it has."],
      'K': ["The kitchen counter. There's a layer of grease that could be carbon dated."],
      'A': ["The sink is full of dishes from... what year is it again?"],
      'G': ["A pile of garbage. Something moved in there..."],
    },
    tileDecorations: {
      'L': '🛋️', 'E': '🛏️', 'F': '🪑', 'V': '📺', 'K': '🍳', 'Q': '🚽', 'A': '🚰', 'G': '🗑️',
    },
    enemies: [
      { name:'Cockroach', emoji:'🪳', level:1, hp:12, atk:4, def:2, spd:8, exp:5, moves:['Skitter','Antenna Whip','Gross Out'], flavor:'A massive roach emerges from the trash!' },
      { name:'Giant Cockroach', emoji:'🪳🪳', level:3, hp:25, atk:7, def:4, spd:10, exp:12, moves:['Swarm Rush','Disease Cloud','Skitter'], flavor:'A roach the size of a shoe appears!' },
      { name:'Trash Golem', emoji:'🗑️👹', level:4, hp:35, atk:9, def:8, spd:2, exp:18, moves:['Trash Smash','Stink Cloud','Garbage Toss'], flavor:'The garbage has come alive!' },
      { name:'Rainbow Shirt Guy', emoji:'🌈🧍', level:2, hp:20, atk:6, def:3, spd:5, exp:8, moves:['Dazzle','Pep Talk','Color Splash'], flavor:'A guy in a rainbow shirt wants to battle!' },
      { name:'Wandering Vagrant', emoji:'🧔', level:3, hp:28, atk:8, def:4, spd:4, exp:14, moves:['Shopping Cart Ram','Spare Change?','Cardboard Shield'], flavor:'A homeless man stumbled in through the window!' },
      { name:'Mold Monster', emoji:'🟢🦠', level:3, hp:22, atk:6, def:6, spd:3, exp:11, moves:['Spore Cloud','Toxic Touch','Spread'], flavor:'The bathroom mold has gained sentience!' },
      { name:'Rat', emoji:'🐀', level:1, hp:10, atk:5, def:2, spd:9, exp:4, moves:['Bite','Tail Whip','Scurry'], flavor:'A rat dashes out from behind the fridge!' },
    ],
    items: [
      { x:9, y:3, name:'Filet-O-Fish', emoji:'🐟', type:'heal', value:15 },
      { x:1, y:12, name:'Lube', emoji:'🧴', type:'atkUp', value:3 },
      { x:17, y:1, name:'Trojan Reds', emoji:'🟥', type:'heal', value:20 },
      { x:12, y:8, name:'Old Filet-O-Fish', emoji:'🐟', type:'heal', value:8 },
      { x:6, y:12, name:'Lube (Half Empty)', emoji:'🧴', type:'atkUp', value:2 },
    ],
    npcs: [
      { x:13, y:3, emoji:'📻', dialog:["An old radio playing static.","Sometimes you can hear faint talk show voices..."] },
    ],
  },

  reseda: {
    name: "Reseda City",
    width: 32, height: 28,
    startPos: { x: 5, y: 3 },
    encounterRate: 0.08,
    tileData: [
      "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
      "T..BBB..TYY.TT....T..RRRR....T.",
      "T..BbB..TYY.TT....T..RRRR.ZZ.T.",
      "T........YY.......T..RRRR.Zz.T.",
      "T....T........T...T..RRRR....T.",
      "RRRRRRRRRRRRRRRRRRRRRR+RRRRRRRT.",
      "T.HH..P.S...T.....S.P..HH..P.T.",
      "T.Hh....S...CCC...S....Hh....T.",
      "T.......SrrrrrrrrrrS..........T.",
      "T.MM.T..S.T..r.T..S.T..BB.P..T.",
      "T.Mm....S....r....S....Bb....T.",
      "T.......S....r....S..........T.",
      "T.......S....r....S..........T.",
      "RRRRRRRRRRRRR+RRRRRRRRRRRRRRRRT.",
      "T.HH..P......r.......P..HH...T.",
      "T.Hh.........r........P.HhWW.T.",
      "T..........P.r..........WWWW.T.",
      "T.HH..T....Nr........PWWWW.P.T.",
      "T.Hh.......r........WWWWP....T.",
      "T.........r.......WWWW..T.HH.T.",
      "T........r......WWWW..P..Hh..T.",
      "T.HH...r......WWWW.T....T...DT.",
      "T.Hh..r.....WWWW....P........T.",
      "T....r....WWWW..P..T...HH.P..T.",
      "T.P.r...WWWW.P..T....P.Hh....T.",
      "T..r..WWWW.T...P..T.....T....T.",
      "T.r.WWWW..T..P..T....T..P..P.T.",
      "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
    ],
    exits: [
      { x: 4, y: 2, toMap: 'apartment', toX: 9, toY: 12, label: "Perry's Apartment" },
      { x: 30, y: 21, toMap: 'palmsprings', toX: 1, toY: 14, label: 'Palm Springs' },
    ],
    tileColors: {
      '.': '#5a9e3a', '#': '#3a6e2a', 'T': '#2d6e1e', 'P': '#2d6e1e',
      'R': '#666', 'r': '#666', '+': '#666', 'S': '#bbb8a0',
      'B': '#995533', 'b': '#8B4513', 'H': '#aa6644', 'h': '#996633',
      'C': '#cc3333', 'c': '#cc3333', 'M': '#887744', 'm': '#776633',
      'W': '#3388cc', 'Y': '#4499dd', 'N': '#8B6914', 'D': '#4a8a3a',
        'Z': '#cc2020', 'z': '#991818',
      },
      solidTiles: new Set(['T', 'P', 'W', 'B', 'C', 'M', 'H', 'Y', 'N', 'Z']),
    encounterTiles: new Set(['.', 'S']),
    interactTiles: {
      'T': ["A tree. Birds are chirping in the branches."],
      'P': ["A palm tree sways in the warm Reseda breeze."],
      'W': ["The LA River. More concrete channel than river."],
      'Y': ["Pierce College pond. Students used to feed ducks here."],
      'B': ["A commercial building. The sign is faded."],
      'H': ["Someone's house. They probably lock their doors around here."],
      'C': ["RESEDA CENTER - Your health has been restored!"],
      'M': ["A small market. Smells like tacos and cheap beer."],
      'N': ["A sign reads: 'Reseda Blvd — The Heart of the Valley'"],
      'Z': ["DENNY'S - Open 24/7. Grand Slams. Coffee. Regret.", "Perry stares at the menu. He can't afford anything. He orders water."],
    },
    tileDecorations: { 'N': '🪧', 'Y': '🌊', 'Z': '🥞' },
    enemies: [
      { name:'Stray Dog', emoji:'🐕', level:2, hp:18, atk:6, def:3, spd:7, exp:7, moves:['Bite','Bark','Tail Whip'], flavor:'A stray dog blocks your path!' },
      { name:'Pigeon Flock', emoji:'🐦🐦🐦', level:2, hp:15, atk:5, def:2, spd:9, exp:6, moves:['Dive Bomb','Coo Chorus','Peck'], flavor:'A flock of aggressive pigeons attacks!' },
      { name:'Skater Punk', emoji:'🛹', level:3, hp:22, atk:7, def:3, spd:8, exp:10, moves:['Board Slam','Kickflip Strike','Grind'], flavor:'A skater punk challenges you!' },
      { name:'Rainbow Shirt Guy', emoji:'🌈🧍', level:3, hp:24, atk:7, def:4, spd:5, exp:10, moves:['Dazzle','Pep Talk','Color Splash'], flavor:'A guy in a rainbow shirt wants to battle!' },
      { name:'Rainbow Shirt Duo', emoji:'🌈🧍🧍', level:5, hp:40, atk:10, def:5, spd:6, exp:22, moves:['Double Dazzle','Fabulous Slam','Pep Talk'], flavor:'Two rainbow shirt guys challenge you!' },
      { name:'Wandering Vagrant', emoji:'🧔', level:3, hp:28, atk:8, def:4, spd:4, exp:14, moves:['Shopping Cart Ram','Spare Change?','Cardboard Shield'], flavor:'A homeless man approaches menacingly!' },
      { name:'Valley Rat', emoji:'🐀', level:2, hp:14, atk:6, def:2, spd:10, exp:5, moves:['Bite','Scurry','Plague Scratch'], flavor:'A Valley rat scurries at you!' },
      { name:'Drifter King', emoji:'🧔👑', level:7, hp:55, atk:13, def:7, spd:5, exp:35, moves:['Dumpster Dive','Street Wisdom','Bindle Whack'], flavor:'The legendary Drifter King has appeared!' },
      { name:'College Student', emoji:'📚🧑', level:4, hp:30, atk:8, def:5, spd:6, exp:15, moves:['Textbook Throw','All-Nighter','Student Debt'], flavor:'A stressed Pierce College student attacks!' },
    ],
    items: [
      { x:14, y:6, name:"McDonald's Filet-O-Fish", emoji:'🐟', type:'heal', value:20 },
      { x:3, y:10, name:'Trojan Reds (3-Pack)', emoji:'🟥', type:'heal', value:12 },
      { x:26, y:6, name:'Industrial Lube', emoji:'🧴', type:'atkUp', value:4 },
      { x:20, y:10, name:'Double Filet-O-Fish', emoji:'🐟', type:'heal', value:25 },
      { x:8, y:17, name:'Trojan Reds (Magnum)', emoji:'🟥', type:'heal', value:15 },
      { x:16, y:20, name:'Soggy Filet-O-Fish', emoji:'🐟', type:'heal', value:8 },
    ],
    npcs: [
      { x:14, y:7, emoji:'🏥', dialog:["Welcome to the Reseda Center!","Your health has been restored!"], action:'heal' },
      { x:3, y:7, emoji:'👴', dialog:["I've lived in Reseda since '72.","It used to be nice... well, nicer anyway.","Watch out for the Drifter King near the river!"] },
      { x:25, y:9, emoji:'👩‍🍳', dialog:["Best tacos in the Valley, right here!","Too bad I can't give you any. Budget cuts."] },
      { x:7, y:17, emoji:'🪧', dialog:["SIGN: 'Reseda Blvd - Est. 1912'","'Home of... well, Perry Caravello lives here.'"] },
      { x:28, y:14, emoji:'🎣', dialog:["I'm fishing in the LA River.","Don't ask what I've caught. You don't wanna know."] },      { x:2, y:3, emoji:'🧔', dialog:["*rustles cardboard blanket*","...spare some change, brother?","I used to sleep inside. Wild times."] },
      { x:6, y:3, emoji:'🧔\u200d♂️', dialog:["Yo... Perry?","You still owe me twenty bucks from last Tuesday.","Also your apartment smells."] },
      { x:3, y:5, emoji:'🛒', dialog:["*loud snoring*","Zzzz... Grand Slam... extra bacon... Zzzzz..."] },
      { x:7, y:4, emoji:'🧔', dialog:["Hey! You got a Filet-O-Fish?","I will literally do anything for a Filet-O-Fish right now.","ANYTHING."] },
      { x:25, y:4, emoji:'👩\u200d🍽️', dialog:["Welcome to Denny's! Open 24 hours!","Coffee's fresh! Well... it was fresh four hours ago.","Grand Slam special: $8.99. Today's your lucky day!"] },    ],
  },

  palmsprings: {
    name: "Palm Springs",
    width: 32, height: 28,
    startPos: { x: 1, y: 14 },
    encounterRate: 0.10,
    tileData: [
      "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
      "^..^^^.PP.OO.PP..^^.JJJ.II.^^.^",
      "^..^^^..P.OO..P..^^.JjJ..I.^^.^",
      "^..^^....OO.......^.JJJ....^^.^",
      "^....P......P...P...........^^.^",
      "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRR^^",
      "^.BB.P..S...T.....S.P..BB..P.^^",
      "^.Bb....S...CCC...S....Bb....^^",
      "^.......SrrrrrrrrrrS..........^",
      "^.MM.P..S.P..r.P..S.P..BB.P..^",
      "^.Mm....S....r....S....Bb....^",
      "^.......S....r....S....X.....^",
      "^..X....S....r....S..........^",
      "RRRRRRRRRRRRR+RRRRRRRRRRRRRRRRR",
      "D.........P..r..P.......X....^",
      "^.kkkk.......r........P......^",
      "^.kWWk..P....r....UU.P.......^",
      "^.kkkk.......r....UU....X..P.^",
      "^..P.........r.......P.......^",
      "^....X...P...r..P............^",
      "RRRRRRRRRRRRR+RRRRRRRRRRRRRRRR^",
      "^..MM.P....r.....X...........^",
      "^..Mm.....r....P......X..P...^",
      "^..P.....r...WWWW............^",
      "^...X...r..WWWWWW..X.......P.^",
      "^..P...r.WWWWWW..P...X.......^",
      "^.....r.WWWW..P..X...........^",
      "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
    ],
    exits: [
      { x: 0, y: 14, toMap: 'reseda', toX: 29, toY: 21, label: 'Reseda City' },
    ],
    tileColors: {
      '.': '#d4b87a', '^': '#8B7355', 'T': '#2d6e1e', 'P': '#2d6e1e',
      'R': '#666', 'r': '#666', '+': '#666', 'S': '#c8c0a0',
      'B': '#bb7744', 'b': '#aa6633', 'H': '#aa6644', 'h': '#996633',
      'C': '#cc3333', 'c': '#cc3333', 'M': '#887744', 'm': '#776633',
      'W': '#3388cc', 'X': '#2d6e1e', 'I': '#ccc', 'J': '#7755aa', 'j': '#6644aa',
      'O': '#44aadd', 'k': '#4a9e3a', 'U': '#aaa', 'N': '#8B6914', 'D': '#d4b87a',
    },
    solidTiles: new Set(['^', 'T', 'P', 'W', 'B', 'C', 'M', 'H', 'J', 'X', 'I', 'O', 'U']),
    encounterTiles: new Set(['.', 'S', 'k']),
    interactTiles: {
      '^': ["Rugged desert mountains. Mt. San Jacinto looms above."],
      'T': ["A rare tree in the desert. It looks thirsty."],
      'P': ["A tall palm tree. Very Palm Springs."],
      'W': ["The LA River... even out here it's mostly concrete."],
      'X': ["A prickly cactus. Don't touch it!"],
      'I': ["A massive wind turbine. It hums with power."],
      'J': ["THE PALM SPRINGS GYM! Defeat the Gym Leader to prove yourself!"],
      'O': ["A sparkling desert oasis pool. Celebrities used to swim here."],
      'U': ["An RV. Someone's living their best life... or their only life."],
      'C': ["PALM SPRINGS CENTER - Desert oasis of healing!"],
      'M': ["Retro Market - Vintage everything!"],
      'k': ["Manicured golf course grass. Oddly pristine in the desert."],
    },
    tileDecorations: { 'X': '🌵', 'I': '💨', 'O': '🏊' },
    enemies: [
      { name:'Scorpion', emoji:'🦂', level:4, hp:20, atk:9, def:5, spd:8, exp:12, moves:['Sting','Pinch','Venom Strike'], flavor:'A scorpion emerges from the sand!' },
      { name:'Coyote', emoji:'🐺', level:5, hp:35, atk:10, def:4, spd:9, exp:18, moves:['Howl','Desert Pounce','Pack Tactics'], flavor:'A desert coyote stalks you!' },
      { name:'Tumbleweed', emoji:'🌀', level:3, hp:18, atk:5, def:7, spd:12, exp:8, moves:['Roll','Desert Wind','Tangle'], flavor:'A sentient tumbleweed rolls into battle!' },
      { name:'Sunburned Tourist', emoji:'🧑‍🦲🌞', level:5, hp:32, atk:9, def:4, spd:4, exp:16, moves:['Complaint','Sunscreen Spray','Camera Flash'], flavor:'A furious sunburned tourist attacks!' },
      { name:'Rainbow Shirt Guy', emoji:'🌈🧍', level:5, hp:32, atk:9, def:5, spd:6, exp:15, moves:['Dazzle','Fabulous Slam','Color Splash'], flavor:'A desert rainbow shirt guy challenges you!' },
      { name:'Desert Vagrant', emoji:'🧔🏜️', level:5, hp:38, atk:10, def:5, spd:4, exp:20, moves:['Sand Throw','Tent Pole Jab','Cardboard Shield'], flavor:'A desert drifter blocks the path!' },
      { name:'Gila Monster', emoji:'🦎', level:6, hp:40, atk:12, def:8, spd:5, exp:25, moves:['Venomous Bite','Tail Whip','Death Roll'], flavor:'A massive Gila Monster slithers out!' },
      { name:'Dust Devil', emoji:'🌪️', level:7, hp:45, atk:11, def:6, spd:11, exp:30, moves:['Sand Blast','Tornado Spin','Desert Fury'], flavor:'A supernatural Dust Devil appears!' },
      { name:'Wind Turbine Golem', emoji:'💨🤖', level:8, hp:60, atk:14, def:10, spd:3, exp:40, moves:['Blade Spin','Electric Surge','Wind Blast'], flavor:'A Wind Turbine has come alive!!' },
      { name:'Rat King', emoji:'🐀👑', level:9, hp:70, atk:16, def:9, spd:7, exp:50, moves:['Rat Swarm','Plague Bite','Tunnel Strike'], flavor:'THE RAT KING EMERGES!' },
    ],
    items: [
      { x:12, y:7, name:'Deluxe Filet-O-Fish', emoji:'🐟', type:'heal', value:25 },
      { x:5, y:10, name:'Desert Lube (SPF 50)', emoji:'🧴', type:'atkUp', value:5 },
      { x:25, y:4, name:'Trojan Reds (Party Pack)', emoji:'🟥', type:'heal', value:20 },
      { x:20, y:16, name:'Leftover Filet-O-Fish', emoji:'🐟', type:'heal', value:18 },
      { x:3, y:16, name:'Premium Lube', emoji:'🧴', type:'atkUp', value:6 },
      { x:15, y:19, name:'Filet-O-Fish Combo', emoji:'🐟', type:'heal', value:30 },
    ],
    npcs: [
      { x:14, y:7, emoji:'🏥', dialog:["Welcome to Palm Springs Center!","Your health has been restored!"], action:'heal' },
      { x:7, y:2, emoji:'🧓', dialog:["I remember when Sinatra used to play here.","Now it's all scorpions and tourists.","Be careful near the Gym — the leader is TOUGH."] },
      { x:19, y:2, emoji:'🏋️', dialog:["THE PALM SPRINGS GYM!","Leader: THE DESERT KING","Think you can handle the heat?"] },
      { x:3, y:21, emoji:'🛒', dialog:["RETRO MARKET","'We sell vintage everything!'","'Everything is vintage when it's this old.'"] },
      { x:20, y:16, emoji:'🧑‍🦳', dialog:["RV life is the life!","No rent, no rules, just rattlesnakes."] },
      { x:3, y:15, emoji:'⛳', dialog:["This golf course costs $200 a round.","Perry can't afford that. He can barely afford ramen."] },
    ],
  },
};
